name: conduit
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  flutter_secure_storage: ^5.0.2
  fpdart: ^0.0.14
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  go_router: ^3.1.0
  hooks_riverpod: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  mockito: ^5.2.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1

  

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # The name  of family is kept generic so that if tommorow we want to change
  # fonts we can change it and we will not have to update it manually in the code.

  fonts:
    - family: AppFontLight
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
    - family: AppFontRegular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: AppFontMedium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: AppFontSemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
    - family: AppFontBold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
  

